services:
  hopship.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=your_database;Username=your_user;Password=your_password
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - rabbitmq
      - postgres  # <-- Assicura che PostgreSQL sia avviato prima della Web API

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    ports:
      - "8001:5432"
    environment:
      POSTGRES_DB: HopShipDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes: 
      - postgres_data:/var/lib/postgresql/data  # Persistenza dei dati

  hopship.worker.database:
    build:
      context: .
      dockerfile: HopShip.Worker.Database/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=HopShipDB;Username=user;Password=password
    depends_on:
      - postgres
    restart: always 

volumes:
  postgres_data:
